<a href="https://colab.research.google.com/github/efsiul/Model-Severity-Accidents/blob/main/02_REDUCIR_DATASET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Pandas library for dataset management and management. Then the dataset that was downloaded from https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents?select=US_Accidents_Dec21_updated.csv is read.

In [ ]:
# Carga nuestros datos reducidos desde GitHub
! git clone https://github.com/cristiancastano852/Model-Severity-Accidents

Cloning into 'Model-Severity-Accidents'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 47 (delta 21), reused 6 (delta 1), pack-reused 0
Unpacking objects: 100% (47/47), 10.84 MiB | 4.41 MiB/s, done.

In [ ]:
import pandas as pd

#Leemos nuestros datos
df = pd.read_csv('/content/Model-Severity-Accidents/Reduced_dataset.csv')
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1786515,2,2020-12-01 12:03:00,2020-12-02 00:09:22,28.257513,-81.436229,28.260315,-81.437122,0.201,Stationary traffic on US-92 W - US-17 S from O...,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-270134,2,2021-12-12 06:17:38,2021-12-12 09:02:47,47.461591,-92.901602,47.477781,-92.902962,1.120,Construction on US-169 near COUNTY HWY-5 Drive...,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-2689947,2,2018-02-12 07:34:42,2018-02-12 13:34:42,37.694424,-122.103225,37.694424,-122.103225,0.000,At 163rd Ave/164th Ave/Carolyn St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
3,A-191424,2,2017-05-19 17:14:48,2017-05-19 23:14:48,42.706440,-73.830750,42.713740,-73.819670,0.756,At RT-5/Wolf Rd/Exit 2 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-2142330,2,2020-06-24 18:29:14,2020-06-24 18:59:14,43.034760,-89.409920,43.034760,-89.409920,0.000,At CR-D/Fish Hatchery Rd/Exit 260 - Accident. ...,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,A-701562,2,2021-11-06 12:56:45.000000,2021-11-06 15:55:28.000000,40.728194,-74.102176,40.723675,-74.089130,0.751,Slow traffic on US-1 Trk N - US-9 Trk N from S...,...,False,False,False,False,False,False,Day,Day,Day,Day
99996,A-743880,2,2021-03-24 05:18:30,2021-03-24 13:54:34,25.809384,-80.323373,25.809874,-80.329373,0.375,Stationary traffic on FL-948 from FL-826/Palme...,...,False,False,False,False,False,False,Night,Night,Night,Night
99997,A-1108176,2,2021-08-16 16:24:24,2021-08-16 17:05:25,38.292666,-77.479169,38.290757,-77.471943,0.413,Stationary traffic on VA-3 - US-1 Bus N from W...,...,False,False,False,False,False,False,Day,Day,Day,Day
99998,A-2255283,2,2020-04-13 19:09:00,2020-04-13 20:07:19,39.622410,-105.195060,39.622450,-105.195010,0.004,At CR-120/S Parmalee Gulch Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-1700839,2,2021-01-09 17:52:35,2021-01-09 19:31:34,35.643350,-78.803974,35.643628,-78.804621,0.041,Incident on BASS LAKE RD near HOUSE 900 Drive ...,...,False,False,False,False,False,False,Night,Night,Day,Day

Once the CSV file has been loaded into a dataframe, the instructions are applied to reduce the dataset size to 100,000 rows using the .sample() method. This is done to be able to upload the dataset to GitHub and later work with it.

In [ ]:
df2 = df.sample(n=100000, random_state=42)

To save the new dataset with a csv extension, the Pandas to_csv() method is used.

In [ ]:
df2.to_csv('Reduced_dataset.csv', index=False)