<a href="https://colab.research.google.com/github/efsiul/Model-Severity-Accidents/blob/main/03_PRE_PROCESADO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Integrantes:**

Luis Felipe Cadavid Chica - 98711955 - Ingenieria de Sistemas.

Cristian Alexander Castaño Montoya - 1001409163 - Ingenieria de Sistemas.

Importing the Pandas library for dataset management and management. Then the dataset that was downloaded from https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents?select=US_Accidents_Dec21_updated.csv is read.

In [1]:
# Carga nuestros datos reducidos desde GitHub
! git clone https://github.com/efsiul/Model-Severity-Accidents

fatal: la ruta de destino 'Model-Severity-Accidents' ya existe y no es un directorio vacío.

## Importación de librerias

In [2]:
import time
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, KFold, ShuffleSplit, StratifiedKFold
from sklearn.preprocessing import OrdinalEncoder, StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer 
from scipy.spatial.distance import cdist 
from scipy.stats import skew, norm
from sklearn.model_selection import train_test_split
from scipy import stats
import warnings
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import accuracy_score

## Cargamos nuestro dataset

In [7]:
#Leemos nuestros datos
df = pd.read_csv('Reduced_dataset.csv')
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1786515,2,2020-12-01 12:03:00,2020-12-02 00:09:22,28.257513,-81.436229,28.260315,-81.437122,0.201,Stationary traffic on US-92 W - US-17 S from O...,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-270134,2,2021-12-12 06:17:38,2021-12-12 09:02:47,47.461591,-92.901602,47.477781,-92.902962,1.120,Construction on US-169 near COUNTY HWY-5 Drive...,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-2689947,2,2018-02-12 07:34:42,2018-02-12 13:34:42,37.694424,-122.103225,37.694424,-122.103225,0.000,At 163rd Ave/164th Ave/Carolyn St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
3,A-191424,2,2017-05-19 17:14:48,2017-05-19 23:14:48,42.706440,-73.830750,42.713740,-73.819670,0.756,At RT-5/Wolf Rd/Exit 2 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-2142330,2,2020-06-24 18:29:14,2020-06-24 18:59:14,43.034760,-89.409920,43.034760,-89.409920,0.000,At CR-D/Fish Hatchery Rd/Exit 260 - Accident. ...,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,A-701562,2,2021-11-06 12:56:45.000000,2021-11-06 15:55:28.000000,40.728194,-74.102176,40.723675,-74.089130,0.751,Slow traffic on US-1 Trk N - US-9 Trk N from S...,...,False,False,False,False,False,False,Day,Day,Day,Day
99996,A-743880,2,2021-03-24 05:18:30,2021-03-24 13:54:34,25.809384,-80.323373,25.809874,-80.329373,0.375,Stationary traffic on FL-948 from FL-826/Palme...,...,False,False,False,False,False,False,Night,Night,Night,Night
99997,A-1108176,2,2021-08-16 16:24:24,2021-08-16 17:05:25,38.292666,-77.479169,38.290757,-77.471943,0.413,Stationary traffic on VA-3 - US-1 Bus N from W...,...,False,False,False,False,False,False,Day,Day,Day,Day
99998,A-2255283,2,2020-04-13 19:09:00,2020-04-13 20:07:19,39.622410,-105.195060,39.622450,-105.195010,0.004,At CR-120/S Parmalee Gulch Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-1700839,2,2021-01-09 17:52:35,2021-01-09 19:31:34,35.643350,-78.803974,35.643628,-78.804621,0.041,Incident on BASS LAKE RD near HOUSE 900 Drive ...,...,False,False,False,False,False,False,Night,Night,Day,Day

## **01. PRE-PROCESAMIENTO**

## Eliminar datos duplicados:

In [ ]:
df.drop_duplicates(inplace=True)
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1786515,2,2020-12-01 12:03:00,2020-12-02 00:09:22,28.257513,-81.436229,28.260315,-81.437122,0.201,Stationary traffic on US-92 W - US-17 S from O...,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-270134,2,2021-12-12 06:17:38,2021-12-12 09:02:47,47.461591,-92.901602,47.477781,-92.902962,1.120,Construction on US-169 near COUNTY HWY-5 Drive...,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-2689947,2,2018-02-12 07:34:42,2018-02-12 13:34:42,37.694424,-122.103225,37.694424,-122.103225,0.000,At 163rd Ave/164th Ave/Carolyn St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
3,A-191424,2,2017-05-19 17:14:48,2017-05-19 23:14:48,42.706440,-73.830750,42.713740,-73.819670,0.756,At RT-5/Wolf Rd/Exit 2 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-2142330,2,2020-06-24 18:29:14,2020-06-24 18:59:14,43.034760,-89.409920,43.034760,-89.409920,0.000,At CR-D/Fish Hatchery Rd/Exit 260 - Accident. ...,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,A-701562,2,2021-11-06 12:56:45.000000,2021-11-06 15:55:28.000000,40.728194,-74.102176,40.723675,-74.089130,0.751,Slow traffic on US-1 Trk N - US-9 Trk N from S...,...,False,False,False,False,False,False,Day,Day,Day,Day
99996,A-743880,2,2021-03-24 05:18:30,2021-03-24 13:54:34,25.809384,-80.323373,25.809874,-80.329373,0.375,Stationary traffic on FL-948 from FL-826/Palme...,...,False,False,False,False,False,False,Night,Night,Night,Night
99997,A-1108176,2,2021-08-16 16:24:24,2021-08-16 17:05:25,38.292666,-77.479169,38.290757,-77.471943,0.413,Stationary traffic on VA-3 - US-1 Bus N from W...,...,False,False,False,False,False,False,Day,Day,Day,Day
99998,A-2255283,2,2020-04-13 19:09:00,2020-04-13 20:07:19,39.622410,-105.195060,39.622450,-105.195010,0.004,At CR-120/S Parmalee Gulch Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-1700839,2,2021-01-09 17:52:35,2021-01-09 19:31:34,35.643350,-78.803974,35.643628,-78.804621,0.041,Incident on BASS LAKE RD near HOUSE 900 Drive ...,...,False,False,False,False,False,False,Night,Night,Day,Day

## Eliminar todas las filas con valores faltantes:

In [8]:
df.dropna(inplace=True)
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1786515,2,2020-12-01 12:03:00,2020-12-02 00:09:22,28.257513,-81.436229,28.260315,-81.437122,0.201,Stationary traffic on US-92 W - US-17 S from O...,...,False,False,False,False,False,False,Day,Day,Day,Day
5,A-1441160,2,2021-11-02 03:16:00,2021-11-02 04:33:30,30.499671,-91.141074,30.502041,-91.141152,0.164,Incident on N FOSTER DR near HOLLYWOOD ST Expe...,...,False,False,False,False,True,False,Night,Night,Night,Night
7,A-472662,2,2021-12-23 17:45:18,2021-12-23 21:10:39,28.450381,-81.399122,28.449707,-81.401108,0.129,Slow traffic on FL-482 - US-92 W - US-441 S - ...,...,False,False,False,False,False,False,Night,Day,Day,Day
15,A-1057215,2,2021-10-19 17:39:00,2021-10-19 19:40:34,33.962013,-118.231992,33.957410,-118.229918,0.340,Slow traffic from E 83rd St to Calden Ave due ...,...,False,False,False,False,False,False,Day,Day,Day,Day
17,A-2362363,2,2020-01-06 10:14:00,2020-01-06 11:27:36,33.977722,-118.075771,33.977722,-118.075771,0.000,At Saragosa St - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99987,A-1774938,2,2020-12-02 14:07:00,2020-12-03 02:04:30,39.957860,-75.608497,39.958806,-75.603472,0.274,Stationary traffic on US-322 Bus W - US-322 Bu...,...,False,False,False,False,True,False,Day,Day,Day,Day
99989,A-1560015,2,2021-02-08 23:39:09,2021-02-09 01:18:06,34.657186,-83.041877,34.655588,-83.039598,0.170,Incident on COMMERCE WAY near SC-11 Drive with...,...,False,False,False,False,False,False,Night,Night,Night,Night
99991,A-1495718,2,2021-11-17 16:05:00,2021-11-17 19:02:54,33.954708,-118.044731,33.952333,-118.041286,0.257,Slow traffic from Santa Fe Springs Rd (Mulberr...,...,False,False,False,False,False,False,Day,Day,Day,Day
99995,A-701562,2,2021-11-06 12:56:45.000000,2021-11-06 15:55:28.000000,40.728194,-74.102176,40.723675,-74.089130,0.751,Slow traffic on US-1 Trk N - US-9 Trk N from S...,...,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-1700839,2,2021-01-09 17:52:35,2021-01-09 19:31:34,35.643350,-78.803974,35.643628,-78.804621,0.041,Incident on BASS LAKE RD near HOUSE 900 Drive ...,...,False,False,False,False,False,False,Night,Night,Day,Day

Como pudimos notar, perdimos bastantes datos, pero al tener un dataset tan grande, nos queda igual 33.306 rows que seran suficiente para nuestro modelo

## Selección de características basada en la correlación

In [9]:
corr_matrix = df.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
df.drop(to_drop, axis=1, inplace=True)
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Number,Street,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1786515,2,2020-12-01 12:03:00,2020-12-02 00:09:22,28.257513,-81.436229,0.201,Stationary traffic on US-92 W - US-17 S from O...,1682.0,Pleasant Hill Rd,...,False,False,False,False,False,False,Day,Day,Day,Day
5,A-1441160,2,2021-11-02 03:16:00,2021-11-02 04:33:30,30.499671,-91.141074,0.164,Incident on N FOSTER DR near HOLLYWOOD ST Expe...,5098.0,Hollywood St,...,False,False,False,False,True,False,Night,Night,Night,Night
7,A-472662,2,2021-12-23 17:45:18,2021-12-23 21:10:39,28.450381,-81.399122,0.129,Slow traffic on FL-482 - US-92 W - US-441 S - ...,1631.0,Sand Lake Rd,...,False,False,False,False,False,False,Night,Day,Day,Day
15,A-1057215,2,2021-10-19 17:39:00,2021-10-19 19:40:34,33.962013,-118.231992,0.340,Slow traffic from E 83rd St to Calden Ave due ...,8404.0,S Alameda St,...,False,False,False,False,False,False,Day,Day,Day,Day
17,A-2362363,2,2020-01-06 10:14:00,2020-01-06 11:27:36,33.977722,-118.075771,0.000,At Saragosa St - Accident.,10882.0,Saragosa St,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99987,A-1774938,2,2020-12-02 14:07:00,2020-12-03 02:04:30,39.957860,-75.608497,0.274,Stationary traffic on US-322 Bus W - US-322 Bu...,299.0,W Market St,...,False,False,False,False,True,False,Day,Day,Day,Day
99989,A-1560015,2,2021-02-08 23:39:09,2021-02-09 01:18:06,34.657186,-83.041877,0.170,Incident on COMMERCE WAY near SC-11 Drive with...,7230.0,S Highway 11,...,False,False,False,False,False,False,Night,Night,Night,Night
99991,A-1495718,2,2021-11-17 16:05:00,2021-11-17 19:02:54,33.954708,-118.044731,0.257,Slow traffic from Santa Fe Springs Rd (Mulberr...,13222.0,Mulberry Dr,...,False,False,False,False,False,False,Day,Day,Day,Day
99995,A-701562,2,2021-11-06 12:56:45.000000,2021-11-06 15:55:28.000000,40.728194,-74.102176,0.751,Slow traffic on US-1 Trk N - US-9 Trk N from S...,182.0,Lincoln Hwy,...,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-1700839,2,2021-01-09 17:52:35,2021-01-09 19:31:34,35.643350,-78.803974,0.041,Incident on BASS LAKE RD near HOUSE 900 Drive ...,839.0,Bass Lake Rd,...,False,False,False,False,False,False,Night,Night,Day,Day

## Convertimos las variables categoricas en variables numericas usando la codificación One-Hot

Reducimos el dataset a 7000, porque el entorno de colab no nos da RAM suficiente para procesar más

In [10]:
df = df.sample(n=7000, random_state=42)

In [11]:
categoricas = list(df.select_dtypes(include=['object']))

In [12]:
df = pd.get_dummies(df, columns=categoricas)

## Normalizamos

In [13]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_df = scaler.fit_transform(df)

In [16]:
scaled_df

array([[0.33333333, 0.5799961 , 0.83866969, ..., 0.        , 1.        ,
        0.        ],
       [0.33333333, 0.54796208, 0.05605576, ..., 1.        , 0.        ,
        1.        ],
       [0.33333333, 0.15662151, 0.76418747, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.33333333, 0.20444528, 0.50978076, ..., 0.        , 1.        ,
        0.        ],
       [0.33333333, 0.40126683, 0.79655724, ..., 1.        , 0.        ,
        1.        ],
       [0.33333333, 0.1521539 , 0.7594973 , ..., 0.        , 1.        ,
        0.        ]])

In [15]:
scaler

MinMaxScaler()

In [17]:
df

,Severity,Start_Lat,Start_Lng,Distance(mi),Number,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),...,Weather_Condition_Wintry Mix,Weather_Condition_Wintry Mix / Windy,Sunrise_Sunset_Day,Sunrise_Sunset_Night,Civil_Twilight_Day,Civil_Twilight_Night,Nautical_Twilight_Day,Nautical_Twilight_Night,Astronomical_Twilight_Day,Astronomical_Twilight_Night
33161,2,38.755849,-76.993077,0.716,9701.0,82.0,51.0,30.05,9.0,12.0,...,0,0,1,0,1,0,1,0,1,0
38051,2,37.983387,-121.260446,0.134,2287.0,45.0,58.0,30.17,10.0,3.0,...,0,0,0,1,0,1,0,1,0,1
59978,2,28.546678,-81.206051,0.154,12210.0,78.0,93.0,29.73,10.0,7.0,...,0,0,1,0,1,0,1,0,1,0
15349,2,35.276799,-80.896911,0.077,5400.0,74.0,97.0,29.08,6.0,5.0,...,0,0,1,0,1,0,1,0,1,0
90318,2,27.821030,-82.680510,0.103,3476.0,55.0,69.0,29.88,10.0,21.0,...,0,0,1,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,2,38.498448,-121.395939,0.164,7048.0,88.0,37.0,29.79,2.0,6.0,...,0,0,1,0,1,0,1,0,1,0
52936,2,38.468005,-121.415495,0.000,7982.0,86.0,36.0,29.89,10.0,3.0,...,0,0,1,0,1,0,1,0,1,0
56268,2,29.699891,-95.596180,0.036,7200.0,92.0,31.0,29.91,10.0,6.0,...,0,0,1,0,1,0,1,0,1,0
85173,2,34.446007,-79.375104,0.446,1236.0,72.0,100.0,29.95,10.0,5.0,...,0,0,0,1,0,1,0,1,0,1
96593,2,28.438947,-81.471343,0.765,8735.0,90.0,48.0,29.91,10.0,9.0,...,0,0,1,0,1,0,1,0,1,0